# Form implementation generated from reading ui file 'dev/addroute.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Route(object):
    def setupUi(self, Route):
        Route.setObjectName("Route")
        Route.resize(786, 592)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Route)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(180, 120, 531, 361))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stations = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        self.stations.setObjectName("stations")
        self.verticalLayout.addWidget(self.stations)
        self.buses = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        self.buses.setObjectName("buses")
        self.verticalLayout.addWidget(self.buses)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(parent=self.verticalLayoutWidget)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.verticalLayout.addWidget(self.dateTimeEdit)
        self.addRouteBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.addRouteBtn.setObjectName("addRouteBtn")
        self.verticalLayout.addWidget(self.addRouteBtn)
        self.backBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.backBtn.setObjectName("backBtn")
        self.verticalLayout.addWidget(self.backBtn)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=Route)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 140, 171, 191))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)

        self.retranslateUi(Route)
        QtCore.QMetaObject.connectSlotsByName(Route)

    def retranslateUi(self, Route):
        _translate = QtCore.QCoreApplication.translate
        Route.setWindowTitle(_translate("Route", "Добавление рейса"))
        self.addRouteBtn.setText(_translate("Route", "Добавить"))
        self.backBtn.setText(_translate("Route", "Назад"))
        self.label.setText(_translate("Route", "Станция"))
        self.label_2.setText(_translate("Route", "Автобус"))
        self.label_3.setText(_translate("Route", "Время отправления"))
