# Form implementation generated from reading ui file 'dev/untitled21.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Bus(object):
    def setupUi(self, Bus):
        Bus.setObjectName("Bus")
        Bus.resize(786, 592)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Bus)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(180, 120, 531, 361))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.brand = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.brand.setObjectName("brand")
        self.verticalLayout.addWidget(self.brand)
        self.stateNumber = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.stateNumber.setObjectName("stateNumber")
        self.verticalLayout.addWidget(self.stateNumber)
        self.busCapacity = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.busCapacity.setText("")
        self.busCapacity.setObjectName("busCapacity")
        self.verticalLayout.addWidget(self.busCapacity)
        self.addBusBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.addBusBtn.setObjectName("addBusBtn")
        self.verticalLayout.addWidget(self.addBusBtn)
        self.backBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.backBtn.setObjectName("backBtn")
        self.verticalLayout.addWidget(self.backBtn)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=Bus)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(34, 150, 141, 221))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)

        self.retranslateUi(Bus)
        QtCore.QMetaObject.connectSlotsByName(Bus)

    def retranslateUi(self, Bus):
        _translate = QtCore.QCoreApplication.translate
        Bus.setWindowTitle(_translate("Bus", "Добавление автобуса"))
        self.addBusBtn.setText(_translate("Bus", "Добавить"))
        self.backBtn.setText(_translate("Bus", "Назад"))
        self.label.setText(_translate("Bus", "Марка"))
        self.label_3.setText(_translate("Bus", "Гос.номер"))
        self.label_4.setText(_translate("Bus", "Вместительность"))
