# Form implementation generated from reading ui file 'dev/delbus.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DelBus(object):
    def setupUi(self, DelBus):
        DelBus.setObjectName("DelBus")
        DelBus.resize(743, 564)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=DelBus)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(120, 90, 471, 371))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        self.delBusBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.delBusBtn.setObjectName("delBusBtn")
        self.verticalLayout.addWidget(self.delBusBtn)
        self.backBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.backBtn.setObjectName("backBtn")
        self.verticalLayout.addWidget(self.backBtn)
        self.label = QtWidgets.QLabel(parent=DelBus)
        self.label.setGeometry(QtCore.QRect(30, 160, 57, 14))
        self.label.setObjectName("label")

        self.retranslateUi(DelBus)
        QtCore.QMetaObject.connectSlotsByName(DelBus)

    def retranslateUi(self, DelBus):
        _translate = QtCore.QCoreApplication.translate
        DelBus.setWindowTitle(_translate("DelBus", "Удаление автобуса"))
        self.delBusBtn.setText(_translate("DelBus", "Удалить"))
        self.backBtn.setText(_translate("DelBus", "Назад"))
        self.label.setText(_translate("DelBus", "Автобус"))
