# Form implementation generated from reading ui file 'dev/main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(788, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 0, 771, 551))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.calcRoutesBtn = QtWidgets.QPushButton(parent=self.frame)
        self.calcRoutesBtn.setGeometry(QtCore.QRect(240, 250, 241, 25))
        self.calcRoutesBtn.setObjectName("calcRoutesBtn")
        self.passangerCountBtn = QtWidgets.QPushButton(parent=self.frame)
        self.passangerCountBtn.setGeometry(QtCore.QRect(240, 300, 241, 25))
        self.passangerCountBtn.setObjectName("passangerCountBtn")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(110, 380, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.addBusBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.addBusBtn.setObjectName("addBusBtn")
        self.verticalLayout.addWidget(self.addBusBtn)
        self.delBusBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.delBusBtn.setObjectName("delBusBtn")
        self.verticalLayout.addWidget(self.delBusBtn)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(300, 380, 160, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.addStationBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.addStationBtn.setObjectName("addStationBtn")
        self.verticalLayout_2.addWidget(self.addStationBtn)
        self.delStationBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.delStationBtn.setObjectName("delStationBtn")
        self.verticalLayout_2.addWidget(self.delStationBtn)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(parent=self.frame)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(510, 380, 160, 80))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.addRouteBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_3)
        self.addRouteBtn.setObjectName("addRouteBtn")
        self.verticalLayout_3.addWidget(self.addRouteBtn)
        self.delRouteBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_3)
        self.delRouteBtn.setObjectName("delRouteBtn")
        self.verticalLayout_3.addWidget(self.delRouteBtn)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 788, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Автовокзал"))
        self.calcRoutesBtn.setText(_translate("MainWindow", "Посчитать рейсы"))
        self.passangerCountBtn.setText(_translate("MainWindow", "Пассажиры"))
        self.addBusBtn.setText(_translate("MainWindow", "Добавить автобус"))
        self.delBusBtn.setText(_translate("MainWindow", "Удалить автобус"))
        self.addStationBtn.setText(_translate("MainWindow", "Добавить станцию"))
        self.delStationBtn.setText(_translate("MainWindow", "Удалить станцию"))
        self.addRouteBtn.setText(_translate("MainWindow", "Добавить рейс"))
        self.delRouteBtn.setText(_translate("MainWindow", "Удалить рейс"))
