# Form implementation generated from reading ui file 'dev/untitled1.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Passenger(object):
    def setupUi(self, Passenger):
        Passenger.setObjectName("Passenger")
        Passenger.resize(400, 300)
        Passenger.setAcceptDrops(False)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Passenger)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(34, 50, 341, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.passengerCounter = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.passengerCounter.setText("")
        self.passengerCounter.setObjectName("passengerCounter")
        self.horizontalLayout.addWidget(self.passengerCounter)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.backBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.backBtn.setObjectName("backBtn")
        self.verticalLayout.addWidget(self.backBtn)

        self.retranslateUi(Passenger)
        QtCore.QMetaObject.connectSlotsByName(Passenger)

    def retranslateUi(self, Passenger):
        _translate = QtCore.QCoreApplication.translate
        Passenger.setWindowTitle(
            _translate("Passenger", "Максимальное количество пассажиров")
        )
        self.label.setText(
            _translate("Passenger", "Максимальное количество пассажиров: ")
        )
        self.backBtn.setText(_translate("Passenger", "Назад"))
